services:
  miniostorage:
    image: minio/minio:latest
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_UI_PORT}:9001"
    env_file:
      - .env
    restart: unless-stopped
    command: server /data --console-address ":9001"
    volumes:
      - "./minio/minio_data:/data"
    networks:
      - webapp
    profiles:
      - internal-dev
      - internal-prod

  psql:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    user: root
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data
    networks:
      - webapp
    profiles:
      - internal-dev
      - internal-prod

  webapp:
    image: webapp
    restart: unless-stopped
    build:
      context: app
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - "DB_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@psql:5432/mydb"
    networks:
      - webapp
    profiles:
      - internal-prod
      - external-prod

networks:
  webapp: