services:

  miniostorage:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    restart: unless-stopped
    command: server /data --console-address ":9001"
    volumes:
      - "./minio/minio_data:/data"
    networks:
      - webapp
    profiles:
      - dev
      - prod

  psql:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    user: root
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data
    networks:
      - webapp
    profiles:
      - dev
      - prod

networks:
  webapp: